directories:
  output: dist
  buildResources: build
appId: com.bomstudios.icepopide
productName: IcepopIDE
copyright: BOM STUDIOS
files:
  - filter:
      - main.js
      - src/**/*
      - Logo.png
win:
  target:
    - target: nsis
      arch:
        - x64
    - target: portable
      arch:
        - x64
  icon: Logo.png
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  installerIcon: Logo.png
  installerHeaderIcon: Logo.png
  createDesktopShortcut: true
  createStartMenuShortcut: true
  shortcutName: IcepopIDE
portable:
  artifactName: IcepopIDE-v2-Portable.exe
electronVersion: 28.3.3
